"""add seen field to messages

Revision ID: 206fea8b31ca
Revises: d2a7dd9d9425
Create Date: 2026-03-30 00:43:44.136511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206fea8b31ca'
down_revision: Union[str, Sequence[str], None] = 'd2a7dd9d9425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('seen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'seen')
    # ### end Alembic commands ###
