"""create users table

Revision ID: df5c7b499ee3
Revises: 2ab3ee2180a7
Create Date: 2026-03-28 00:26:36.238780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5c7b499ee3'
down_revision: Union[str, Sequence[str], None] = '2ab3ee2180a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_table_id'), 'test_table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_table_id'), table_name='test_table')
    op.drop_table('test_table')
    # ### end Alembic commands ###
